import React, { useState } from 'react';
import { ChevronDownIcon, ChevronUpIcon } from './IconComponents';

export const AboutContent: React.FC = () => (
  <div className="space-y-4 text-slate-300">
    <h2 className="text-2xl font-bold text-yellow-400">What is Vivid Trails?</h2>
    <p className="leading-relaxed">
      Vivid Trails is an AI-powered travel-vlog platform that automatically transforms your trip photos into stunning interactive maps, compelling stories, and shareable highlight reels.
    </p>
    <p className="leading-relaxed">
      Our mission is to make travel journaling effortless and beautiful. Just upload your photos with location data, and our intelligent system crafts a narrative of your adventure, grouping your pictures by location and writing descriptive stories for each stop. You can then watch an AI-generated video reel of your trip, share your story with friends, or compete in photo competitions with the community.
    </p>
    <p className="leading-relaxed">
      Relive your journeys and share them with the world like never before.
    </p>
  </div>
);

const FaqItem: React.FC<{ q: string, a: React.ReactNode }> = ({ q, a }) => {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="border-b border-slate-700">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex justify-between items-center text-left py-4"
      >
        <h3 className="font-semibold text-white text-lg">{q}</h3>
        {isOpen ? <ChevronUpIcon className="w-5 h-5 text-yellow-400 flex-shrink-0 ml-4" /> : <ChevronDownIcon className="w-5 h-5 text-slate-400 flex-shrink-0 ml-4" />}
      </button>
      <div className={`grid grid-rows-[0fr] transition-all duration-300 ${isOpen ? 'grid-rows-[1fr]' : ''}`}>
        <div className="overflow-hidden">
            <div className="pb-4 text-slate-400 leading-relaxed">{a}</div>
        </div>
      </div>
    </div>
  )
}

export const FAQContent: React.FC = () => (
  <div className="space-y-0">
    <FaqItem
      q="How does the AI story generation work?"
      a={<p>Our AI analyzes the GPS coordinates from your photos to understand your travel route. It then groups photos from nearby locations into "stops" on your journey. Using this geographical data, it writes a creative title, summary, and short stories for each stop, weaving them together into a complete travelogue.</p>}
    />
    <FaqItem
      q="What kind of photos should I upload for the best results?"
      a={<p>For the best experience, upload original, unedited photos directly from your camera or smartphone with location services (GPS tagging) enabled. This metadata is crucial for our AI to build your map and story accurately.</p>}
    />
    <FaqItem
      q="Is my data and are my photos private?"
      a={<p>Your privacy is important. By default, your created trips are private to your profile. You can choose to publish them to make them visible to the community on the Explore page. We securely store your photos and do not share your data with third parties.</p>}
    />
    <FaqItem
      q="Can I edit the trip story generated by the AI?"
      a={<p>Yes! After the AI generates your trip, you can enter 'Edit Mode' on the trip detail page. This allows you to change the title, summary, location names, and stories to better reflect your personal memories.</p>}
    />
     <FaqItem
      q="What are photo competitions?"
      a={<p>Competitions are themed photo contests hosted by the Vivid Trails community. You can submit your best shots to win bragging rights and get your work recognized. To ensure fairness, we only allow original photos with camera metadata (EXIF data) to be submitted.</p>}
    />
  </div>
);

export const ContactContent: React.FC = () => (
  <div className="space-y-4 text-slate-300">
     <h2 className="text-2xl font-bold text-yellow-400">Get in Touch</h2>
    <p className="leading-relaxed">
      Have questions, feedback, or just want to say hello? We'd love to hear from you.
    </p>
    <ul className="space-y-2 list-inside">
      <li><strong>Email:</strong> <a href="mailto:graphynovus@gmail.com" className="text-yellow-400 hover:underline">graphynovus@gmail.com</a></li>
      <li><strong>Website:</strong> <a href="https://graphynovus.vercel.app" target="_blank" rel="noopener noreferrer" className="text-yellow-400 hover:underline">graphynovus.vercel.app</a></li>
    </ul>
     <p className="leading-relaxed">
      Follow our journey and connect with us on our platforms to stay updated with the latest features and community highlights.
    </p>
  </div>
);
